# Generated by Django 4.1.2 on 2022-10-05 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_warehouse_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 13, 49, 4, 646220)),
        ),
    ]
