# Generated by Django 4.1.2 on 2022-10-05 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_status_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 14, 24, 1, 241797)),
        ),
    ]
