# Generated by Django 4.1.1 on 2022-11-27 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_client_photo_alter_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 18, 42, 45, 344826)),
        ),
    ]
